### ISSUE TITLE
[Feature request] Possibility to auto-close the invalid pull request

### ISSUE THREAD

**Issue by smay1613** [seferov/pr-lint-action#17]
Please, consider adding such features:
- [ ] Auto-close invalid pull request (configurable) https://github.com/seferov/pr-lint-action/issues/19
- [ ] Custom comment (provided by workflow)
- [ ] PR description linting too
- [ ] Post a comment

**Comment by seferov** [comment]
Hey @smay1613 

Thank you for good ideas 👍  I think it is better to split these into separate feature requests. I can start with "auto-close invalid pull request"
