### ISSUE TITLE
Optional inputs are not defined 

### ISSUE THREAD

**Issue by jaredmcateer** [seferov/pr-lint-action#231]
Using the optional inputs results in a warning:

`Warning: Unexpected input(s) 'title-regex-flags', 'error-message', valid inputs are ['entryPoint', 'args', 'title-regex']`

I assume this is because they are not present in the actions.yml file but I am inexperienced with writing github actions.

**Comment by cobrabr** [comment]
I'm also running into this issue. It seems like the error message does work, however.
